# Generated by Django 3.1.2 on 2021-11-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
