# Generated by Django 3.1.2 on 2021-11-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
