# Generated by Django 3.1.2 on 2021-11-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userpreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
