# Generated by Django 3.1.2 on 2021-11-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userpreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
