# Generated by Django 3.1.2 on 2021-11-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0012_auto_20211120_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('feature_preference', models.TextField()),
                ('actor_preference', models.TextField()),
                ('director_preference', models.TextField()),
                ('studio_preference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=250)),
                ('trailer_link', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=450)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('production_company', models.CharField(max_length=150)),
                ('actors', models.ManyToManyField(to='main.Actor')),
                ('directors', models.ManyToManyField(to='main.Director')),
                ('genre', models.ManyToManyField(to='main.Genre')),
            ],
        ),
    ]
